### ISSUE TITLE
Android demo编译不过

### ISSUE THREAD

**Issue by lijintan1990** [Tencent/tgfx#229]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"&ninja zlibstatic
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
[1/16] Building C object CMakeFiles/zlibstatic.dir/compress.c.o
[2/16] Building C object CMakeFiles/zlibstatic.dir/adler32.c.o
[3/16] Building C object CMakeFiles/zlibstatic.dir/crc32.c.o
[4/16] Building C object CMakeFiles/zlibstatic.dir/gzclose.c.o
[5/16] Building C object CMakeFiles/zlibstatic.dir/gzlib.c.o
[6/16] Building C object CMakeFiles/zlibstatic.dir/gzwrite.c.o
[7/16] Building C object CMakeFiles/zlibstatic.dir/gzread.c.o
[8/16] Building C object CMakeFiles/zlibstatic.dir/inffast.c.o
[9/16] Building C object CMakeFiles/zlibstatic.dir/infback.c.o
[10/16] Building C object CMakeFiles/zlibstatic.dir/zutil.c.o
[11/16] Building C object CMakeFiles/zlibstatic.dir/inftrees.c.o
[12/16] Building C object CMakeFiles/zlibstatic.dir/uncompr.c.o
[13/16] Building C object CMakeFiles/zlibstatic.dir/deflate.c.o
[14/16] Building C object CMakeFiles/zlibstatic.dir/trees.c.o
[15/16] Building C object CMakeFiles/zlibstatic.dir/inflate.c.o
[16/16] Linking C static library libz.a
C:\Users\ws\AppData\Local\Android\Sdk\ndk\19.2.5345600\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip.exe -S E:\statics\tgfx\third_party\out\zlib\android\build-zlibstatic\arm64\**********************************************************************
[8/246] Linking CXX static library tgfx\tgfx-drawers.a
FAILED: tgfx/CMakeFiles/tgfx-vendor tgfx/CMakeFiles/tgfx-vendor.dir/libtgfx-vendor.a tgfx/CMakeFiles/tgfx-vendor.dir/.vendor.md5 E:/statics/tgfx/android/app/.cxx/Debug/o235o3g6/arm64-v8a/tgfx/CMakeFiles/tgfx-vendor E:/statics/tgfx/android/app/.cxx/Debug/o235o3g6/arm64-v8a/tgfx/CMakeFiles/tgfx-vendor.dir/libtgfx-vendor.a E:/statics/tgfx/android/app/.cxx/Debug/o235o3g6/arm64-v8a/tgfx/CMakeFiles/tgfx-vendor.dir/.vendor.md5 
cmd.exe /C "cd /D E:\statics\tgfx && C:\Users\ws\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake.exe -E env CMAKE_ANDROID_NDK=C:/Users/ws/AppData/Local/Android/Sdk/ndk/19.2.5345600 node E:/statics/tgfx/third_party/vendor_tools/vendor-build -p android -a arm64 -v -o E:/statics/tgfx/android/app/.cxx/Debug/o235o3g6/arm64-v8a/tgfx/CMakeFiles/tgfx-vendor.dir libpng zlib freetype pathkit skcms"
ninja: build stopped: subcommand failed.

C++ build system [build] failed while executing:
    @echo off
    "C:\\Users\\ws\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      -C ^
      "E:\\statics\\tgfx\\android\\app\\.cxx\\Debug\\o235o3g6\\arm64-v8a" ^
      hello2d
  from E:\statics\tgfx\android\app
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

C:\Users\ws\AppData\Local\Android\Sdk\ndk\19.2.5345600\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip.exe: 'E:\statics\tgfx\third_party\out\zlib\android\build-zlibstatic\arm64\**********************************************************************': No such file
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:274)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:106)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:104)
	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess(ExecuteProcess.kt:104)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess$default(ExecuteProcess.kt:84)
	at com.android.build.gradle.internal.cxx.build.CxxRegularBuilder.executeProcessBatch(CxxRegularBuilder.kt:331)
	at com.android.build.gradle.internal.cxx.build.CxxRegularBuilder.build(CxxRegularBuilder.kt:128)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask$doTaskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:70)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.doTaskAction(ExternalNativeBuildTask.kt:145)
	at com.android.build.gradle.internal.tasks.UnsafeOutputsTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:65)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.internal.tasks.UnsafeOutputsTask.taskAction(UnsafeOutputsTask.kt:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	... 113 more
Caused by: com.android.ide.common.process.ProcessException: Error while executing process C:\Users\ws\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe with arguments {-C E:\statics\tgfx\android\app\.cxx\Debug\o235o3g6\arm64-v8a hello2d}
	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:269)
	... 130 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\ws\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
	... 131 more

**Comment by domchen** [comment]
你手动在tgfx根目录里运行一下 `node build_vendor -p android libpng zlib`, 贴出详细报错内容。

**Comment by domchen** [comment]
我刚刚在Windows电脑上测试了最新的main分支代码是能正常编译运行的。检查一下是否修改了项目配置，比如不要点击那个Gradle升级的提示。

**Comment by domchen** [comment]
长期无进一步信息反馈，问题先关闭，有补充可重新打开。
