### ISSUE TITLE
web目录下执行 npm run build 报错

### ISSUE THREAD

**Issue by wuyasong** [Tencent/tgfx#52]
tgfx版本: 1.0.0
node版本：14/16 都不行

> tgfx@1.0.0 build
> node script/build.demo.js && npm run build:tgfx && rollup -c ./script/rollup.demo.js

emcmake cmake -S /Users/apple/Documents/code/open-code/tgfx/web/demo -B /Users/apple/Documents/code/open-code/tgfx/web/demo/cmake-build-release -G Ninja -DCMAKE_BUILD_TYPE=Releaseconfigure: cmake -S /Users/apple/Documents/code/open-code/tgfx/web/demo -B /Users/apple/Documents/code/open-code/tgfx/web/demo/cmake-build-release -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/apple/Documents/code/open-code/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-threads
The DEPS config requires a higher version of depsync tool: /Users/apple/Documents/code/open-code/tgfx/DEPS
Requires version: 1.3.12
Current version: 1.3.11
Please update the depsync tool and try again.
TGFX_USE_OPENGL: ON
TGFX_USE_QT: OFF
TGFX_USE_SWIFTSHADER: OFF
TGFX_USE_FREETYPE: OFF
TGFX_USE_PNG_DECODE: 
TGFX_USE_PNG_ENCODE: 
TGFX_USE_JPEG_DECODE: 
TGFX_USE_JPEG_ENCODE: 
TGFX_USE_WEBP_DECODE: ON
TGFX_USE_WEBP_ENCODE: 
TGFX_BUILD_TESTS: OFF
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/apple/Documents/code/open-code/tgfx/web/demo/cmake-build-release
[0/2] Generating tgfx-vendor
[2/2] Linking CXX executable hello2d.js
FAILED: hello2d.js 
: && /Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG --no-entry -lembind -sEXPORT_NAME='Hello2D' -sWASM=1 -sASYNCIFY     -sUSE_WEBGL2=1 -sEXPORTED_RUNTIME_METHODS=['GL','Asyncify'] -sALLOW_MEMORY_GROWTH=1     -sMODULARIZE=1 -sENVIRONMENT='web,worker' -sEXPORT_ES6=1 -sUSE_ES6_IMPORT_META=0 -Oz CMakeFiles/hello2d.dir/src/TGFXView.cpp.o -o hello2d.js  tgfx/tgfx-drawers.a  tgfx/tgfx.a && :
em++: warning: cannot check node version: [Errno 2] No such file or directory: '/Users/apple/Documents/code/open-code/emsdk/node/14.18.2_64bit/bin/node' [-Wversion-check]
Traceback (most recent call last):
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/emcc.py", line 1208, in run
    phase_post_link(options, state, wasm_target, wasm_target, target)
  File "/Users/apple/Documents/code/open-code/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/emcc.py", line 2883, in phase_post_link
    phase_emscript(options, in_wasm, wasm_target, memfile)
  File "/Users/apple/Documents/code/open-code/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/emcc.py", line 2913, in phase_emscript
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/emscripten.py", line 892, in run
    emscript(in_wasm, out_wasm, outfile_js, memfile)
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/emscripten.py", line 371, in emscript
    glue, forwarded_data = compile_settings()
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/emscripten.py", line 201, in compile_settings
    out = shared.run_js_tool(path_from_root('src/compiler.js'),
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/tools/shared.py", line 245, in run_js_tool
    check_node()
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/tools/shared.py", line 269, in helper
    result = func()
  File "/Users/apple/Documents/code/open-code/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/tools/shared.py", line 348, in check_node
    check_node_version()
  File "/Users/apple/Documents/code/open-code/emsdk/upstream/emscripten/tools/shared.py", line 340, in check_node_version
    if version < MINIMUM_NODE_VERSION:
UnboundLocalError: local variable 'version' referenced before assignment
ninja: build stopped: subcommand failed.
node:child_process:935
    throw err;
    ^

Error: Command failed: cmake --build /Users/apple/Documents/code/open-code/tgfx/web/demo/cmake-build-release --target hello2d
    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at Object.<anonymous> (/Users/apple/Documents/code/open-code/tgfx/web/script/build.demo.js:51:14)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 39473,
  stdout: null,
  stderr: null
}

**Comment by domchen** [comment]
注意看报错提示：

The DEPS config requires a higher version of depsync tool: /Users/apple/Documents/code/open-code/tgfx/DEPS
Requires version: 1.3.12
Current version: 1.3.11
Please update the depsync tool and try again.

这是因为你的 depsync 工具版本太低了，第三方依赖没有同步成功。用 npm install -g depsync 重新安装一下。再到项目根目录运行一遍 depsync。每次更新代码都要重新运行一下 depsync 同步第三方依赖，再编译。
